prompts:
  - "{{query}}"

evaluateOptions:
  maxConcurrency: 6

providers:
  - id: python:./provider.py
    label: 'Agent: deepseek-v4-flash'
    config:
      model_name: 'deepseek/deepseek-v4-flash'
      local: false

  #- id: python:./extractor_provider.py
  #  label: 'Extractor: deepseek-v4-flash'
  #  config:
  #    model_name: 'deepseek/deepseek-v4-flash'
  #    local: false

  #- id: python:./provider.py
  #  label: 'Agent: granite4'
  #  config:
  #    model_name: "granite4:3b"
  #    local: true

  #- id: python:./extractor_provider.py
  #  label: 'Extractor: granite4'
  #  config:
  #    model_name: "granite4:3b"
  #    local: true
  
defaultTest:
  assert:
    - type: python
      value: file://assertions.py:promptfoo_execution_accuracy

tests:
  - ./tests.yaml
