prompts:
  - "{{query}}"

evaluateOptions:
  maxConcurrency: 5

providers:
  - id: python:./provider.py
    label: 'Agent: gpt-4o'
    config:
      model_name: 'gpt-4o'
      local: false

  - id: python:./provider.py
    label: 'Agent: qwen2.5'
    config:
      model_name: "qwen2.5:7b"
      local: true

  - id: python:./provider.py
    label: 'Agent: granite3.1-dense'
    config:
      model_name: "granite3.1-dense:8b"
      local: true

  - id: python:./provider.py
    label: 'Agent: granite3.3'
    config:
      model_name: "granite3.3:8b"
      local: true

  - id: python:./provider.py
    label: 'Agent: llama3.1'
    config:
      model_name: "llama3.1:8b"
      local: true

tests:
  - vars:
      id: example-001
      description: "Time series test case"
      query: "Time series by month of total_parcels"
      ground_truth: "0104.10.10"

  - vars:
      id: example-002
      description: "Underperforming providers test case"
      query: "List the top 5 underperforming logistics providers by average bwt in jan"
      ground_truth: "90.25"
